export const BOARD_IDENTIFIER = {
  BOARD_REPOSITORY: Symbol('BOARD_REPOSITORY'),
  BOARD_SERVICE: Symbol('BOARD_SERVICE'),
};

export const USER_IDENTIFIER = {
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  USER_SERVICE: Symbol('USER_SERVICE'),
};

export const TASK_IDENTIFIER = {
  TASK_REPOSITORY: Symbol('TASK_REPOSITORY'),
  TASK_SERVICE: Symbol('TASK_SERVICE'),
};

export const SERVICE_IDENTIFIER = {
  AUTH_SERVICE: Symbol('AUTH_SERVICE'),
  LOGGER_SERVICE: Symbol('LOGGER_SERVICE'),
};
